// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgXPpEE4o6ThpOjnW152zx7faxwkCOFAM',
    appId: '1:904490804072:web:da5a53c4057efa8d64acdd',
    messagingSenderId: '904490804072',
    projectId: 'mad-cw-6',
    authDomain: 'mad-cw-6.firebaseapp.com',
    storageBucket: 'mad-cw-6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS1qLxq0yEFQXkV20zXgUJG9jOHj_2Pio',
    appId: '1:904490804072:android:10895d977642300364acdd',
    messagingSenderId: '904490804072',
    projectId: 'mad-cw-6',
    storageBucket: 'mad-cw-6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfZMF4FgvXpPsalu-jgj1s6jI5m2NUfJU',
    appId: '1:904490804072:ios:8ef63a52ab4ba0b764acdd',
    messagingSenderId: '904490804072',
    projectId: 'mad-cw-6',
    storageBucket: 'mad-cw-6.firebasestorage.app',
    iosBundleId: 'com.example.madCw6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfZMF4FgvXpPsalu-jgj1s6jI5m2NUfJU',
    appId: '1:904490804072:ios:8ef63a52ab4ba0b764acdd',
    messagingSenderId: '904490804072',
    projectId: 'mad-cw-6',
    storageBucket: 'mad-cw-6.firebasestorage.app',
    iosBundleId: 'com.example.madCw6',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgXPpEE4o6ThpOjnW152zx7faxwkCOFAM',
    appId: '1:904490804072:web:e85453a50b548f2a64acdd',
    messagingSenderId: '904490804072',
    projectId: 'mad-cw-6',
    authDomain: 'mad-cw-6.firebaseapp.com',
    storageBucket: 'mad-cw-6.firebasestorage.app',
  );
}
